export const ADD_TO_CART = 'ADD_TO_CART'
export const CHANGE_MSG = 'CHANGE_MSG'
export const DELETE_PRODUCT_ON_CART = 'DELETE_PRODUCT_ON_CART'

export const INCREASE_AMOUNT_PRODUCT_ON_CART = 'INCREASE_AMOUNT_PRODUCT_ON_CART'
export const DECREASE_AMOUNT_PRODUCT_ON_CART = 'DECREASE_AMOUNT_PRODUCT_ON_CART'

export const BUY = 'BUY'